
#This is a staging environment
[env.staging]
d1_databases = [
    { binding = "jahir_db", database_name = "jahir_staging_db", database_id = "any" },
]

# # This is a production environment
[env.dev]
d1_databases = [
    { binding = "jahir_db", database_name = "jahir_local_db", database_id = "jahir_local_db", preview_database_id = "jahir_local_db" },
]
