name = "jahir"
compatibility_date ="2023-08-14"
compatibility_flags = [ "nodejs_compat" ]
#This is a staging environment
# [[d1_databases]]
# binding = "jahir_prod_db"
# database_name = "jahir_staging_db"
# database_id = "6445c89a-67ce-4de6-841c-42d2c7e3d103"

# prod
[[d1_databases]]
binding = "jahir_prod_db"
database_name = "jahir_prod_db"
database_id = "8548a0a7-3567-4b54-860f-3be10cffc6bc"
preview_database_id = "jahir_prod_db"


#This is a staging environment
# [env.staging]
# d1_databases = [
#     { binding = "jahir_prod_db", database_name = "jahir_staging_db", database_id = "6445c89a-67ce-4de6-841c-42d2c7e3d103" },
# ]

# # This is a dev environment
# [env.dev]
# d1_databases = [
#     { binding = "jahir_prod_db", database_name = "jahir_prod_db", database_id = "jahir_prod_db",preview_database_id="jahir_prod_db" },
# ]
# # This is a production environment
# [env.dev]
# d1_databases = [
#     { binding = "jahir_prod_db", database_name = "jahir_prod_db", database_id = "8548a0a7-3567-4b54-860f-3be10cffc6bc",preview_database_id="jahir_prod_db" },
# ]
